### PR TITLE
Document Node

### LINKED ISSUE #18: Update documentation for Node
Most of it is outdated or wrong.

### PR DESCRIPTION
**Pull request by Stronkkey**
Fixes #18
The documentation is not quite finished but it's alright

### CODE REVIEW

File: scene/main/node.hpp [hunk 1]
```diff
@@ -111,152 +206,154 @@ typedef std::unordered_set<Node*> children_t;
...
 
 	/**
-	* Deletes this node and removes it as a child from the parent.
+	* @brief Removes this node as a child from the parent.
 	*/
 	virtual ~Node();
 
 	/**
-	* Emitted when the node is ready. Called after _ready callback and follows the same rules.
+	* @brief Emitted when the node is ready. Called after _ready callback and follows the same rules.
```
Comment (Stronkkey) [inline scene/main/node.hpp:214]:
```suggestion
	* @brief Emitted when the node is ready. Called after the @b _ready callback and follows the same rules.
```

File: scene/main/node.hpp [hunk 2]
```diff
@@ -111,152 +206,154 @@ typedef std::unordered_set<Node*> children_t;
...
 
 	/**
-	* Sends the given @param what notification to the node, calling _notification with @param what.
+	* @brief Sends the given notification to the node, as well as calling _notification with @b what .
 	*/
 	void notification(const int what);
 
 	/**
-	* Calls notification with @param what to itself and all children.
+	* @brief Calls notification with @b what to itself and all children.
```
Comment (Stronkkey) [inline scene/main/node.hpp:271]:
```suggestion
	* @brief Calls notification with @b what to itself and all descendants.
```

File: scene/main/node.hpp [hunk 3]
```diff
@@ -111,152 +206,154 @@ typedef std::unordered_set<Node*> children_t;
...
+	* Use is_queued_for_deletion to check whether an node will be deleted at the end of the frame.
 	* The node will only be freed after all other deferred calls are finished.
+	* @note The behavior is undefined the Node is not heap allocated.
 	*/
 	void queue_free();
 
 	/**
-	* @returns true if the node is queued for deletion.
+	* @brief Returns @b true if the node is queued for deletion.
+	* @see @b queue_free .
```
Comment (Stronkkey) [inline scene/main/node.hpp:286]:
```suggestion
	* @see @b queue_free.
```

File: scene/main/node.hpp [hunk 4]
```diff
@@ -111,152 +206,154 @@ typedef std::unordered_set<Node*> children_t;
...
+	* @brief Adds a child @b node .
+	* @details This methods overwrites the parent of the @b node .
 	*/
 	void add_child(Node *child);
 
 	/**
-	* Removes the @param child as a child from this node and sets the parent and tree property to nullptr.
-	* Does nothing if the child does not exist or is not a parent of this node.
+	* @brief Removes the Node @b child from this Node.
+	* @details If the @b child Node is inside the SceneTree, then the SceneTree of the @b child Node will be set to @b nullptr .
```
Comment (Stronkkey) [inline scene/main/node.hpp:336]:
```suggestion
	* @details If the @b child Node is inside the SceneTree, then the SceneTree will be set to @b nullptr.
```

File: scene/main/node.hpp [hunk 5]
```diff
@@ -111,152 +206,154 @@ typedef std::unordered_set<Node*> children_t;
...
+	* Does nothing if the parent of the @b child Node is not this Node.
 	*/
 	void remove_child(Node *child);
 
 	/**
-	* @returns all children.
+	* @brief Returns an implementation defined contianer of all children.
```
Comment (Stronkkey) [inline scene/main/node.hpp:342]:
```suggestion
	* @brief Returns an implementation defined container of all children.
```

File: scene/main/node.hpp [hunk 6]
```diff
@@ -111,152 +206,154 @@ typedef std::unordered_set<Node*> children_t;
...
-	* @returns the parent of this node.
+	* @brief Returns the parent of this Node.
 	*/
 	constexpr Node *get_parent() const {
 		return parent;
 	}
 
 	/**
-	* Calls remove_child on all the children of this node.
+	* @brief Removes all children from this Node by calling remove_child on them.
```
Comment (Stronkkey) [inline scene/main/node.hpp:356]:
```suggestion
	* @brief Removes all children from this Node.
```
